### PR TITLE
Calm the hell down Everbot.

### PR DESCRIPTION
**Pull request by dannygreg**
The poor thing feels like this:

### CODE REVIEW

**Comment by dirk** [comment]
OMG that .gif. :heart:

**Comment by taylorlapeyre** [comment]
how everbot actually is:

giphy

**Comment by taylorlapeyre** [comment]
also @dannygreg I highly recommend setting it to only_mentions and seeing how that is. Everbot is really useful for that specific use case.

**Comment by thenanyu** [comment]
+1

**Comment by dannygreg** [comment]
> I highly recommend setting it to only_mentions and seeing how that is.



I use the GitHub notifications UI to view them when I have time. I dislike being interrupted; GitHub is inherently asynchronous.

**Comment by thenanyu** [comment]
fair enough merge when ready

**Pull request merged**
